## The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
## 
## 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
## 
## Let us list the factors of the first seven triangle numbers:
## 
##  1: 1
##  3: 1,3
##  6: 1,2,3,6
## 10: 1,2,5,10
## 15: 1,3,5,15
## 21: 1,3,7,21
## 28: 1,2,4,7,14,28
## We can see that 28 is the first triangle number to have over five divisors.
## 
## What is the value of the first triangle number to have over five hundred divisors?

require 'spec_helper'
require 'p012'

describe P012 do

  let( :p012 ){ P012.new }

  it 'says hi in old english' do
    expect(p012.say_hi).to eq 'ho'
  end

  it 'finds the number of divisors of 1' do
    expect(p012.num_divisors(1)).to eq 1
  end

  it 'finds the number of divisors of 10' do
    expect(p012.num_divisors(10)).to eq 4
  end

  it 'finds the first triangle number to have over 1 divisor' do
    expect(p012.triangle(1)).to eq 3 
  end

  it 'finds the first triangle number to have over 5 divisors' do
    expect(p012.triangle(5)).to eq 28
  end

  #it 'finds the first triangle number to have over 2 divisors' do
  #  expect(p012.triangle(2)).to eq 6
  #end


end
